- name: check for kubelet config
  stat:
    path: /etc/kubernetes/kubelet.conf
  register: kubelet

- block:
  - name: kubeadm init
    command: kubeadm init --skip-preflight-checks --token={{ kubernetes_token }} --kubernetes-version=v{{ kubernetes_version }}  --apiserver-advertise-address={{ ansible_eth1.ipv4.address }}

  - name: create root kube dir
    file:
      path: /root/.kube
      state: directory
      owner: root
      group: root

  - name: create root kube config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /root/.kube/config
      remote_src: True
      owner: root
      group: root

  - name: create user kube dir
    file:
      path: /home/vagrant/.kube
      state: directory
      owner: vagrant
      group: vagrant

  - name: create user kube config
    copy:
      src: /etc/kubernetes/admin.conf
      dest: /home/vagrant/.kube/config
      remote_src: True
      owner: vagrant
      group: vagrant
  when: not kubelet.stat.exists

- name: create weave network
  command: kubectl apply -f https://git.io/weave-kube-1.6

- name: get dns service address
  shell: kubectl get services --all-namespaces | grep kube-dns | awk "{print \$3}"
  register: kubednsaddress

- name: wait for dns to be ready
  wait_for: host={{ kubednsaddress.stdout }} port=53 state=started timeout=1800

- include: yum_cache.yml
  when: vagrant_cache

#- name: save iptables
#  command: service iptables save
